services:

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: equitab_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    ports:
      - "9000:9000"
      - "8080:8080"
    networks:
      - equitab_network

  postgres:
    image: postgres:16-alpine
    container_name: equitab_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: equitab
      POSTGRES_USER: equitab_user
      POSTGRES_PASSWORD: secret
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - equitab_network

  redis:
    image: redis:7-alpine
    container_name: equitab_redis
    restart: unless-stopped
    networks:
      - equitab_network

volumes:
  postgres_data:

networks:
  equitab_network:
    driver: bridge
